
2019-10-05 06:14:12.339057:
    metric: ultrametric
    edges:  undirected
    weight: logdegree
    nodes:  FCG_co/FCG_co_uris.txt
    graph:  FCG_co/FCG_co_edgelist.npy
    input:  FCG/Intersect_true_pairs_FCG_IDs.txt
    output: FCG/Intersect_true_pairs_FCG_co_IDs.json
2019-10-05 06:14:12.339345: reading nodes from text file..
2019-10-05 06:14:12.488746: reading graph from text file..
2019-10-05 06:14:12.591024: reading input..
2019-10-05 06:14:12.747323: launching pool of 12 workers.
There was an error in the pool.

real	0m56.795s
user	0m3.411s
sys	0m1.194s

2019-10-05 06:14:16.144706:
    metric: ultrametric
    edges:  undirected
    weight: logdegree
    nodes:  FCG_co/FCG_co_uris.txt
    graph:  FCG_co/FCG_co_edgelist.npy
    input:  FCG_co/Intersect_false_pairs_FCG_IDs.txt
    output: FCG_co/Intersect_false_pairs_FCG_co_IDs.json
2019-10-05 06:14:16.144910: reading nodes from text file..
2019-10-05 06:14:16.145677: reading graph from text file..
2019-10-05 06:14:16.161717: reading input..
Traceback (most recent call last):
  File "/N/u/zkachwal/Carbonate/miniconda3/envs/env-kl/bin/klinker", line 11, in <module>
    load_entry_point('knowledge-linker==0.1rc0', 'console_scripts', 'klinker')()
  File "/N/u/zkachwal/Carbonate/miniconda3/envs/env-kl/lib/python2.7/site-packages/knowledge_linker/frontend/cmdline.py", line 39, in main
    args.func(args)
  File "/N/u/zkachwal/Carbonate/miniconda3/envs/env-kl/lib/python2.7/site-packages/knowledge_linker/frontend/linkpred.py", line 208, in main
    df = pd.read_csv(ns.inputpath, names=names, converters=convs, sep=' ')
  File "/N/u/zkachwal/Carbonate/miniconda3/envs/env-kl/lib/python2.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/N/u/zkachwal/Carbonate/miniconda3/envs/env-kl/lib/python2.7/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/N/u/zkachwal/Carbonate/miniconda3/envs/env-kl/lib/python2.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/N/u/zkachwal/Carbonate/miniconda3/envs/env-kl/lib/python2.7/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/N/u/zkachwal/Carbonate/miniconda3/envs/env-kl/lib/python2.7/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: [Errno 2] File FCG_co/Intersect_false_pairs_FCG_IDs.txt does not exist: 'FCG_co/Intersect_false_pairs_FCG_IDs.txt'

real	0m1.475s
user	0m0.495s
sys	0m0.932s
